version: '3'

services:

  client:
    container_name: client
    build: ./client
    ports: 
      - '$CLIENT_PORT:7500'
    env_file:
      - .env
    restart:
      on-failure
  
  # api:
  #   container_name: api
  #   build: ./api
  #   ports:
  #     - '8080:8080'
  #   env_file:
  #     - .env.production
  
  # db:
  #   container_name: db
  #   build: ./db
  #   ports:
  #     - '${DB_PORT}:5432'