module.exports = {
  id: 183177,
  join_date: 'Mar 26, 2020',
  last_login_date: 'Mar 26, 2020 @ 02:51',
  bikes: [
    {
      bike_id: 'b246653',
      name: 'bikey bike',
      b_brand: null,
      b_model: null,
      description: null,
      frame_type: null,
      b_dist_at_add: '544.7',
      b_time_at_add: '43.8',
      b_dist_current: '1634.1',
      b_time_current: '131.5',
      image_url: null,
      b_date_added: 'Mar 26, 2020',
      b_status: 'active',
      parts: [{
        part_id: 1,
        p_bike_id: 'b246653',
        type: 'chain',
        custom_type: null,
        p_brand: 'shimano',
        p_model: 'xtr',
        p_dist_at_add: 0,
        p_time_at_add: 0,
        lifespan_dist: 300,
        lifespan_time: 1000,
        tracking_method: 'custom',
        useage_metric: 'dist',
        initial_wear_method: 'new',
        p_dist_current: 200,
        p_time_current: 800,
        new_date: 'Mar 01, 2019',
        p_date_added: 'Mar 01, 2019',
        p_status: 'active'

      }]
    },
    {
      bike_id: 'b75929',
      name: 'airborne',
      b_brand: null,
      b_model: null,
      description: null,
      frame_type: null,
      b_dist_at_add: '634.9',
      b_time_at_add: '34.2',
      b_dist_current: '1904.8',
      b_time_current: '102.6',
      image_url: null,
      b_date_added: 'Mar 26, 2020',
      b_status: 'active',
      parts: []
    },
    {
      bike_id: 'b6854565',
      name: 'Juliana',
      b_brand: null,
      b_model: null,
      description: null,
      frame_type: null,
      b_dist_at_add: '0.0',
      b_time_at_add: '0.0',
      b_dist_current: '0.0',
      b_time_current: '0.0',
      image_url: null,
      b_date_added: 'Mar 26, 2020',
      b_status: 'active',
      parts: []
    },
    {
      bike_id: 'b75928',
      name: 'baby blue',
      b_brand: null,
      b_model: null,
      description: null,
      frame_type: null,
      b_dist_at_add: '1539.8',
      b_time_at_add: '125.1',
      b_dist_current: '4619.3',
      b_time_current: '375.4',
      image_url: null,
      b_date_added: 'Mar 26, 2020',
      b_status: 'active',
      parts: []
    }
  ],
  measure_pref: 'km'
}