export const SET_AUTH_STATUS = "SET_AUTH_STATUS";
export const SET_STRAVA_ACCESS_STATUS = "SET_STRAVA_ACCESS_STATUS";
export const SET_USER_DATA = "GET_USER_DATA";
export const SET_USERNAME = "SET_USERNAME";